//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 03:29:32 PM MESZ 
//


package com.w3schools;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.w3schools package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.w3schools
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Chefkoch.Rezept.Zubereitung }
     * 
     */
    public Chefkoch.Rezept.Zubereitung createChefkochRezeptZubereitung() {
        return new Chefkoch.Rezept.Zubereitung();
    }

    /**
     * Create an instance of {@link Chefkoch.Rezept.Kommentare }
     * 
     */
    public Chefkoch.Rezept.Kommentare createChefkochRezeptKommentare() {
        return new Chefkoch.Rezept.Kommentare();
    }

    /**
     * Create an instance of {@link Chefkoch }
     * 
     */
    public Chefkoch createChefkoch() {
        return new Chefkoch();
    }

    /**
     * Create an instance of {@link Chefkoch.Rezept.Zutatenliste.Zutat }
     * 
     */
    public Chefkoch.Rezept.Zutatenliste.Zutat createChefkochRezeptZutatenlisteZutat() {
        return new Chefkoch.Rezept.Zutatenliste.Zutat();
    }

    /**
     * Create an instance of {@link Chefkoch.Rezept.Zutatenliste }
     * 
     */
    public Chefkoch.Rezept.Zutatenliste createChefkochRezeptZutatenliste() {
        return new Chefkoch.Rezept.Zutatenliste();
    }

    /**
     * Create an instance of {@link Chefkoch.Rezept.Info }
     * 
     */
    public Chefkoch.Rezept.Info createChefkochRezeptInfo() {
        return new Chefkoch.Rezept.Info();
    }

    /**
     * Create an instance of {@link Chefkoch.Rezept }
     * 
     */
    public Chefkoch.Rezept createChefkochRezept() {
        return new Chefkoch.Rezept();
    }

}
